name: blog
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7
  - notebook
  - pip
  - pillow
  - pylint
  - docutils
  - aiohttp
  - doit
  - conda-forge::rstcheck
  - conda-forge::doc8
  - conda-forge::watchdog
  - conda-forge::pandoc
  - conda-forge::pandocfilters
  - pip:
    - Nikola
