[theme]
inherit = basic
stylesheet = css/main.css
pygments_style = a11y-dark
pygments_dark_style = a11y-dark

[options]
show_toc_level = 2
analytics_id =
logo =
logo_link =
icon_links =
github_url =
mastodon_url =
x_url =
facebook_url =
youtube_url =
linkedin_url =
google_adsense_id =
plausible_domain =
plausible_src = https://plausible.io/js/script.js
posthog_api_key =
posthog_host = https://us.i.posthog.com
posthog_src = https://us.i.posthog.com/static/array.js
