"""Performance optimizer -- post-build HTML processing.

All operations here run on the *finished* HTML output because they
target markup generated by Jinja templates or by the HTML writer, which
cannot be intercepted at the doctree level:

1. **WebP conversion** -- Converts images in ``_images/`` to WebP and
   rewrites ``src`` references in HTML.  Sphinx provides no hook between
   ``post_process_images()`` (URI resolution) and ``write_doc()``
   (rendering), so the URI rewrite must happen post-build.
2. **Script deferring** -- Adds ``defer`` to ``<script>`` tags injected
   by Sphinx base templates (not present in the doctree).
3. **Asset pruning** -- Removes ``<link>``/``<script>`` tags that
   templates include unconditionally but the page does not use.
4. **Admonition i18n** -- Translates admonition titles rendered by the
   HTML writer (the admonition *type* is a doctree concept, but the
   displayed title comes from the writer).
5. **Minification** -- Minifies all HTML, CSS, and JS.

.. note::

   Image attribute injection (``loading="lazy"``, ``width``/``height``)
   is handled at the doctree level by ``cosmoblog.transforms``.
"""

import base64
from concurrent.futures import ThreadPoolExecutor
import hashlib
import io
import mimetypes
import os
from pathlib import Path
import re

import minify_html
from PIL import Image
from sphinx.application import Sphinx
from sphinx.util.logging import getLogger

from .i18n import get_admonition_map, get_known_langs

logger = getLogger(__name__)

# Sphinx scripts that load synchronously in <head> and can be safely deferred
_DEFERRABLE_SCRIPTS = {
    "documentation_options.js",
    "doctools.js",
    "sphinx_highlight.js",
    "translations.js",
    "design-tabs.js",
}

# Conservative minify-html configuration — safe for all browsers
_MINIFY_CFG = {
    "minify_css": True,
    "minify_js": True,
    "keep_closing_tags": True,
    "keep_html_and_head_opening_tags": True,
    "minify_doctype": True,
}

# CSS/JS files that can be conditionally removed from pages.
# Each entry maps a filename substring to HTML markers that indicate usage.
_PRUNABLE_ASSETS = {
    "mystnb.": {"cell_input", "cell_output", "nb-cell", "cell tag_"},
    "sphinx-design.min.css": {"sd-tab-set", "sd-card", "sd-dropdown", "sd-col"},
    "pygments.css": {'class="highlight'},
}

# CSS files to always remove (redundant with theme dark-only pygments.css)
_ALWAYS_REMOVE = {"pygments_dark.css", "basic.css"}

# Image extensions eligible for WebP conversion
_CONVERTIBLE_EXTS = {".png", ".jpg", ".jpeg"}


def post_process_html(app: Sphinx, exception: Exception | None) -> None:
    """Unified ``build-finished`` handler for all HTML optimizations.

    Called by the theme's ``post_build`` pipeline after pygments CSS
    generation and sitemap creation.  Execution order:

    1. Convert images to WebP.
    2. Post-process HTML (defer, WebP URI rewrite, prune, i18n, minify).
    3. Minify standalone CSS/JS files.
    """
    if exception:
        return

    outdir = Path(app.outdir)

    # --- 1. Convert images to WebP ---
    webp_count, webp_saved = _convert_images_to_webp(outdir)

    # --- 2. Bundle theme CSS files ---
    _bundle_theme_css(outdir)

    # --- 3. Post-process HTML files ---
    html_files = list(outdir.rglob("*.html"))
    defer_count, prune_count, html_bytes_saved = (
        _process_html_files(html_files, webp_count, app)
    )

    # --- 4. Minify standalone CSS/JS files ---
    static_files, static_bytes = _minify_static_files(outdir)

    total_saved = html_bytes_saved + static_bytes + webp_saved
    logger.info(
        "optimizer: defer=%d, pruned=%d refs, "
        "minified=%d static, webp=%d images, "
        "saved=%.1f KB (html=%.1f, static=%.1f, webp=%.1f)",
        defer_count,
        prune_count,
        static_files,
        webp_count,
        total_saved / 1024,
        html_bytes_saved / 1024,
        static_bytes / 1024,
        webp_saved / 1024,
        type="optimizer",
        subtype="information",
    )

    # --- 4. Delete always-removed CSS files from _static ---
    for filename in _ALWAYS_REMOVE:
        dead = outdir / "_static" / filename
        if dead.exists():
            dead.unlink()


def _process_html_files(
    html_files: list[Path],
    webp_count: int,
    app: Sphinx,
) -> tuple[int, int, int]:
    """Apply defer, WebP URI rewriting, pruning, admonition i18n, minification.

    Lazy loading and image dimensions are handled by cosmoblog doctree
    post-transforms before rendering.

    Returns ``(defer_count, prune_count, bytes_saved)``.
    """
    defer_count = 0
    prune_count = 0
    html_bytes_saved = 0

    # Pre-compute admonition maps for all languages.
    default_lang = app.config.blog_default_language
    confdir = str(app.confdir)
    outdir = Path(app.outdir)
    known_langs = get_known_langs(app)
    admonition_maps: dict[str, dict[str, str]] = {}
    for lang in known_langs:
        if lang == default_lang:
            continue
        amap = get_admonition_map(lang, confdir)
        if amap:
            admonition_maps[lang] = amap

    for html_file in html_files:
        content = html_file.read_text(encoding="utf-8")
        original = content
        original_size = len(content.encode("utf-8"))

        new_content = _defer_sphinx_scripts(content)
        if new_content != content:
            defer_count += 1
            content = new_content

        new_content, pruned = _prune_unused_assets(content)
        if pruned > 0:
            prune_count += pruned
            content = new_content

        # Bundle CSS: replace individual links with theme.bundle.css
        content = _update_css_links(content)

        # Deduplicate viewport meta tags (Sphinx basic emits one,
        # sphinxext-opengraph may inject another via metatags).
        content = _dedup_viewport_meta(content)

        # Rewrite image references to WebP
        if webp_count > 0:
            content = _update_image_references(content)

        # Extract base64 images from excerpts
        content = _extract_base64_excerpts(content, outdir, html_file)

        # Fix excerpt images that point to source paths instead of _images/
        content = _fix_excerpt_image_paths(content)

        # Translate admonition titles for the page's language
        if admonition_maps:
            page_lang = _detect_page_lang(
                html_file, outdir, known_langs, default_lang,
            )
            if page_lang in admonition_maps:
                content = _translate_admonitions(
                    content, admonition_maps[page_lang],
                )

        try:
            content = minify_html.minify(content, **_MINIFY_CFG)
        except Exception:
            logger.debug(
                "optimizer: skipped HTML minification for %s",
                html_file,
                type="optimizer",
                subtype="debug",
            )

        if content != original:
            html_file.write_text(content, encoding="utf-8")
            html_bytes_saved += original_size - len(content.encode("utf-8"))

    return defer_count, prune_count, html_bytes_saved


def _detect_page_lang(
    html_file: Path,
    outdir: Path,
    known_langs: set[str],
    default_lang: str,
) -> str:
    """Detect a page's language from its path relative to outdir."""
    try:
        rel = html_file.relative_to(outdir)
        first_part = rel.parts[0] if rel.parts else ""
        if first_part in known_langs:
            return first_part
    except ValueError:
        pass
    return default_lang


def _translate_admonitions(
    content: str,
    admonition_map: dict[str, str],
) -> str:
    """Replace admonition titles in HTML for non-default language pages."""
    for src_title, dst_title in admonition_map.items():
        if src_title.endswith(" "):
            pattern = re.compile(
                r'(<div\s+class="admonition\b[^"]*">\s*'
                r'<p\s+class="admonition-title">)'
                + re.escape(src_title)
                + r'([^<]+</p>)',
                re.DOTALL,
            )
            content = pattern.sub(
                rf'\g<1>{dst_title}\2',
                content,
            )
        else:
            pattern = re.compile(
                r'(<div\s+class="admonition\b[^"]*">\s*'
                r'<p\s+class="admonition-title">)'
                + re.escape(src_title)
                + r'(</p>)',
                re.DOTALL,
            )
            content = pattern.sub(
                rf'\g<1>{dst_title}\2',
                content,
            )
    return content


# ── WebP conversion ──────────────────────────────────────────────────────

# Compression effort 4 is the sweet spot: method=6 costs 2x time for only
# 1.3% smaller output (benchmarked: 13.6s vs 7.4s for 62 KB difference).
_WEBP_METHOD = 4
_WEBP_QUALITY = 85

# Pillow releases the GIL during C-level libwebp encoding, so threads
# provide real parallelism.  Cap at 4 to limit memory pressure.
_WEBP_WORKERS = min(os.cpu_count() or 2, 4)


def _convert_single_image(img_path: Path) -> tuple[int, int]:
    """Convert a single image to WebP.  Thread-safe.

    Returns ``(1, bytes_saved)`` on success, ``(0, 0)`` on skip/error.
    """
    webp_path = img_path.with_suffix(".webp")

    # Reuse already-converted files (from previous build)
    if (
        webp_path.exists()
        and webp_path.stat().st_mtime >= img_path.stat().st_mtime
    ):
        saved = img_path.stat().st_size - webp_path.stat().st_size
        img_path.unlink()
        return 1, saved

    original_size = img_path.stat().st_size
    is_lossless = img_path.suffix.lower() == ".png"

    try:
        with Image.open(img_path) as img:
            if img.mode in ("RGBA", "P"):
                save_img = img.convert("RGBA")
            else:
                save_img = img.convert("RGB")

            save_img.save(
                webp_path,
                "WEBP",
                lossless=is_lossless,
                quality=_WEBP_QUALITY,
                method=_WEBP_METHOD,
            )

        saved = original_size - webp_path.stat().st_size
        img_path.unlink()
        return 1, saved
    except Exception:
        logger.debug(
            "optimizer: skipped WebP conversion for %s",
            img_path,
            type="optimizer",
            subtype="debug",
        )
        return 0, 0


def _convert_images_to_webp(outdir: Path) -> tuple[int, int]:
    """Convert PNG/JPEG images in ``_images/`` to WebP.

    Only operates on the output directory — source tree is untouched.
    Uses a thread pool for parallel encoding (Pillow releases the GIL
    during C-level libwebp calls).

    Returns a tuple of (files_converted, bytes_saved).
    """
    images_dir = outdir / "_images"
    if not images_dir.is_dir():
        return 0, 0

    candidates = [
        p for p in images_dir.iterdir()
        if p.suffix.lower() in _CONVERTIBLE_EXTS
    ]
    if not candidates:
        return 0, 0

    with ThreadPoolExecutor(max_workers=_WEBP_WORKERS) as pool:
        results = list(pool.map(_convert_single_image, candidates))

    converted = sum(r[0] for r in results)
    bytes_saved = sum(r[1] for r in results)
    return converted, bytes_saved


# ── WebP URI rewriting ───────────────────────────────────────────────────


def _update_image_references(content: str) -> str:
    """Replace image file extensions in HTML for converted ``_images/`` files.

    Only rewrites paths containing ``_images/`` to avoid breaking
    references to logos, favicons, and other static assets.
    """
    return re.sub(
        r'(_images/[^"]*)\.(?:png|jpe?g)',
        r"\1.webp",
        content,
    )


# ── Viewport deduplication ────────────────────────────────────────────────


def _dedup_viewport_meta(content: str) -> str:
    """Keep only the first ``<meta name="viewport" ...>`` tag.

    Sphinx basic/layout.html hardcodes one viewport meta, and
    sphinxext-opengraph may inject a second via the ``metatags``
    context variable.  Only the first occurrence is kept.
    """
    matches = list(re.finditer(
        r'<meta[^>]*name=["\']?viewport["\']?[^>]*/?>',
        content,
        re.IGNORECASE,
    ))
    if len(matches) <= 1:
        return content
    # Remove all but the first
    for m in reversed(matches[1:]):
        content = content[:m.start()] + content[m.end():]
    return content


# ── Defer, pruning ───────────────────────────────────────────────────────


def _defer_sphinx_scripts(content: str) -> str:
    """Add ``defer`` attribute to synchronous Sphinx scripts in ``<head>``."""
    for script_name in _DEFERRABLE_SCRIPTS:
        pattern = re.compile(
            rf'<script(?!\s+defer)(\s+src="[^"]*{re.escape(script_name)}[^"]*")>',
            re.IGNORECASE,
        )
        content = pattern.sub(r"<script defer\1>", content)
    return content


def _prune_unused_assets(content: str) -> tuple[str, int]:
    """Remove ``<link>``/``<script>`` for CSS/JS not used by the page."""
    pruned = 0

    for filename in _ALWAYS_REMOVE:
        # Robust regex: handles single/double/no quotes and query parameters
        pattern = re.compile(
            rf'<link[^>]*href=["\']?[^"\' >]*{re.escape(filename)}[^"\' >]*["\']?[^>]*>',
            re.IGNORECASE,
        )
        new_content = pattern.sub("", content)
        if new_content != content:
            pruned += 1
            content = new_content

    for filename_substr, markers in _PRUNABLE_ASSETS.items():
        page_uses_asset = any(marker in content for marker in markers)
        if not page_uses_asset:
            css_pattern = re.compile(
                rf'<link[^>]*href=["\']?[^"\' >]*{re.escape(filename_substr)}[^"\' >]*["\']?[^>]*>',
                re.IGNORECASE,
            )
            new_content = css_pattern.sub("", content)

            js_pattern = re.compile(
                rf'<script[^>]*src=["\']?[^"\' >]*{re.escape(filename_substr)}[^"\' >]*["\']?[^>]*>'
                r"</script>",
                re.IGNORECASE,
            )
            new_content = js_pattern.sub("", new_content)

            if new_content != content:
                pruned += 1
                content = new_content

    return content, pruned


# ── Static file minification ─────────────────────────────────────────────


def _minify_static_files(outdir: Path) -> tuple[int, int]:
    """Minify standalone CSS and JS files in ``_static/``."""
    static_dir = outdir / "_static"
    if not static_dir.is_dir():
        return 0, 0

    files_minified = 0
    bytes_saved = 0

    for filepath in static_dir.rglob("*"):
        if not filepath.is_file():
            continue
        if filepath.suffix not in (".css", ".js"):
            continue

        original = filepath.read_text(encoding="utf-8")
        original_size = len(original.encode("utf-8"))

        suffix = filepath.suffix
        if suffix == ".css":
            wrapped = f"<style>{original}</style>"
        else:
            wrapped = f"<script>{original}</script>"

        try:
            minified_wrapped = minify_html.minify(
                wrapped,
                minify_css=True,
                minify_js=True,
            )
            if suffix == ".css":
                minified = minified_wrapped[7:-8]
            else:
                minified = minified_wrapped[8:-9]

            minified_size = len(minified.encode("utf-8"))
            saved = original_size - minified_size

            if saved > 0:
                filepath.write_text(minified, encoding="utf-8")
                files_minified += 1
                bytes_saved += saved
        except Exception:
            logger.debug(
                "optimizer: skipped minification for %s",
                filepath,
                type="optimizer",
                subtype="debug",
            )

    return files_minified, bytes_saved


# ── CSS Bundling ─────────────────────────────────────────────────────────


def _bundle_theme_css(outdir: Path) -> None:
    """Combine main.css, content.css, and components.css into theme.bundle.css."""
    static_dir = outdir / "_static" / "css"
    if not static_dir.is_dir():
        return

    bundle_path = static_dir / "theme.bundle.css"
    
    # Order matters: main -> content -> components
    files = ["main.css", "content.css", "components.css"]
    combined = []
    
    for f in files:
        fpath = static_dir / f
        if fpath.is_file():
            content = fpath.read_text(encoding="utf-8")
            combined.append(f"/* bundle:{f} */\n" + content)
            
    if combined:
        bundle_path.write_text("\n".join(combined), encoding="utf-8")
        logger.info("optimizer: created CSS bundle theme.bundle.css")


def _update_css_links(content: str) -> str:
    """Replace individual theme CSS links with a single bundle link."""
    # Remove content.css and components.css
    for css in ["content.css", "components.css"]:
        pattern = re.compile(
            rf'<link[^>]*href=["\']?[^"\' >]*{re.escape(css)}[^"\' >]*["\']?[^>]*>',
            re.IGNORECASE,
        )
        content = pattern.sub("", content)
        
    # Replace main.css with theme.bundle.css
    pattern = re.compile(
        r'(<link[^>]*href=["\']?[^"\' >]*)main\.css([^"\' >]*["\']?[^>]*>)',
        re.IGNORECASE,
    )
    return pattern.sub(r"\1theme.bundle.css\2", content)


def _extract_base64_excerpts(content: str, outdir: Path, html_file: Path) -> str:
    """Find base64 images in excerpts, save to files, and update src."""
    excerpts_dir = outdir / "_images" / "excerpts"
    
    # Supports quoted or unquoted attributes (common after minification).
    pattern = re.compile(
        r'(<img[^>]*class=["\']?cosmoblog-post-excerpt["\']?[^>]*src=["\'])'
        r'(data:image/[^"\' >]+)(["\'][^>]*>)',
        re.IGNORECASE,
    )
    
    def replacer(match: re.Match) -> str:
        prefix, src, suffix = match.groups()
        if not src.startswith("data:image/"):
            return match.group(0)
            
        try:
            if "," not in src:
                return match.group(0)
                
            _header, encoded = src.split(",", 1)
            data = base64.b64decode(encoded)
            
            img = Image.open(io.BytesIO(data))
            sha = hashlib.sha256(data).hexdigest()[:12]
            filename = f"{sha}.webp"
            if not excerpts_dir.exists():
                excerpts_dir.mkdir(parents=True, exist_ok=True)
            filepath = excerpts_dir / filename
            if not filepath.exists():
                # Save as WebP with 85% quality for optimal balance
                img.save(filepath, "WEBP", quality=85)
                logger.info(
                    "optimizer: [%s] extracted base64 image to excerpts/%s",
                    html_file.name,
                    filename,
                )
            # Use root-relative path for the excerpt image
            return f"{prefix}/_images/excerpts/{filename}{suffix}"
        except Exception as e:
            logger.warning("optimizer: failed to extract base64 image: %s", e)
            return match.group(0)
            
    return pattern.sub(replacer, content)


def _fix_excerpt_image_paths(content: str) -> str:
    """Fix excerpt images pointing to source paths to point to /_images/."""
    # Pattern matches images in excerpts that don't point to _images/
    pattern = re.compile(
        r'(<img[^>]*class=["\']?cosmoblog-post-excerpt["\']?[^>]*src=["\']?)'
        r'(/(?:es|en|images)/[^"\' >]+)(\.[a-z0-9]+)(["\']?[^>]*>)',
        re.IGNORECASE,
    )

    def replacer(match: re.Match) -> str:
        prefix, path, ext, suffix = match.groups()
        # Extract basename
        basename = Path(path).name
        # We assume all post images are moved to _images/
        return f"{prefix}/_images/{basename}{ext}{suffix}"

    return pattern.sub(replacer, content)
